version: "3"
services:
    app:
        image: golden-path
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        ports:
            - "3000:3000"
        depends_on:
            - mongodb

    mongodb:
        image: "bitnami/mongodb:latest"
        ports:
            - "27017:27017"
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
            - MONGODB_REPLICA_SET_MODE=primary
            - MONGODB_ROOT_USER=taha
            - MONGODB_ROOT_PASSWORD=taha
            - MONGODB_REPLICA_SET_KEY=replicasetkey123
        volumes:
            - "mongo-db:/bitnami/mongodb"

volumes:
    mongo-db:
